version: '3'

services:
  ms_reviews:
    container_name: 'ms_reviews'
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    volumes:
      - .:/app
    links:
      - reviews_db
    depends_on:
      - reviews_db
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DATABASE_URL: mysql://root:password@reviews_db:3306/reviews
      NODE_ENV: docker-compose

  reviews_zookeeper:
    image: quay.io/debezium/zookeeper:1.9.4.Final
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    volumes:
      - zookeeperData:/zookeeper/data
      - zookeeperTxns:/zookeeper/txns
      - zookeeperLogs:/zookeeper/logs

  reviews_db:
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reviews
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  reviews_kafka:
    image: quay.io/debezium/kafka:1.9.4.Final
    ports:
     - 9092:9092
    links:
     - reviews_zookeeper
    volumes:
      - kafkadata:/kafka/data
      - kafkaLogs:/kafka/logs
    environment:
     - ZOOKEEPER_CONNECT=reviews_zookeeper:2181

  reviews_kafka-ui:
    container_name: bl-review-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    links:
     - reviews_zookeeper
     - reviews_kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: reviews_kafka:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      KAFKA_CLUSTERS_0_ZOOKEEPER: reviews_zookeeper:2181

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - 6831:6831/udp # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - 6832:6832/udp # accept jaeger.thrift in binary Thrift protocol used by Node.js Jaeger client (because thriftrw npm package does not support compact protocol)
      - 5775:5775/udp # accept zipkin.thrift in compact Thrift protocol (deprecated; only used by very old Jaeger clients, circa 2016)
      - 5778:5778 # serve configs, sampling strategies
      - 16686:16686 # UI port
      - 14269:14269 # collector admin port: health check at / and metrics at /metrics
      - 14268:14268
    environment:
      - MEMORY_MAX_TRACES=100000

volumes:
  kafkadata:
  kafkaLogs:
  zookeeperData:
  zookeeperLogs:
  zookeeperTxns:
  db:
    driver: local
