# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - service.yaml
  - deployment.yaml
  - migrate.yaml

# namespace to deploy all Resources to
namespace: blue-lightning

